USE [master]
GO

/****** Object:  Database [DB_Shop]    Script Date: 14.01.2018 22:47:12 ******/
CREATE DATABASE [DB_Shop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_Shop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\DB_Shop.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DB_Shop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\DB_Shop_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DB_Shop] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_Shop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_Shop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_Shop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_Shop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_Shop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_Shop] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_Shop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_Shop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_Shop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_Shop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_Shop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_Shop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_Shop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_Shop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_Shop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_Shop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_Shop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_Shop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_Shop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_Shop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_Shop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_Shop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_Shop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_Shop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_Shop] SET  MULTI_USER 
GO

ALTER DATABASE [DB_Shop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_Shop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_Shop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_Shop] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DB_Shop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_Shop] SET  READ_WRITE 
GO

